---
swagger: "2.0"
info:
  description: "API for My"
  version: "2016-10-13T23:04:43Z"
  title: "My API"
host: "abcdef.execute-api.us-east-1.amazonaws.com"
basePath: "/poc"
schemes:
- "https"
paths:
  /{folder}/{item}:
    put:
      produces:
      - "application/json"
      parameters:
      - name: "Content-Type"
        in: "header"
        required: false
        type: "string"
      - name: "item"
        in: "path"
        required: true
        type: "string"
      - name: "folder"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Content-Length:
              type: "string"
            Content-Type:
              type: "string"
        "400":
          description: "400 response"
        "500":
          description: "500 response"
      security:
      - api_key: []
      x-amazon-apigateway-integration:
        credentials: "arn:aws:iam::123123123:role/My-APIGateway-access-role"
        httpMethod: "PUT"
        uri: "arn:aws:apigateway:us-east-1:s3:path/{bucket}/{object}"
        responses:
          "4\\d{2}":
            statusCode: "400"
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Content-Type: "integration.response.header.Content-Type"
              method.response.header.Content-Length: "integration.response.header.Content-Length"
          "5\\d{2}":
            statusCode: "500"
        requestParameters:
          integration.request.path.object: "method.request.path.item"
          integration.request.path.bucket: "method.request.path.folder"
          integration.request.header.Content-Type: "method.request.header.Content-Type"
        passthroughBehavior: "when_no_match"
        type: "aws"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
x-amazon-apigateway-binary-media-types:
- "application/json"
